trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    dotnet clean
    dotnet build
    dotnet test
    dotnet pack -c Release
    dotnet nuget push .\Build\Interactive.Console.*.nupkg -k oy2n5yh3prwrymdvixnaodahjyz7kghudn2ke7ma47tdsa -s https://api.nuget.org/v3/index.json